gui:
    win_title: BSP Viewer
    win_width: 1600
    win_height: 900
    
    imgui_scale: 0 # zero to auto scale based on display DPI
    imgui_font_path: "assets:fonts/CascadiaMono-Regular.ttf"
    imgui_font_size: 14.0  # Size without scaling

appfw:
    extcon_port: 27333
    
rad:
    # The gamma value for gamma correction. Don't really need to change it.
    gamma: 2.2

    # Reflectivity multiplier
    reflectivity: 1
    
    # Base surface reflectivity (will be replaced by materials)
    base_reflectivity: 0.4
    
    # Divisor of default light_environment brightness
    light_env_brightness_divisor: 140
    
    # Brightness multiplier relative to sun brightness
    sky_light_brightness_multiplier: 0.3

commands:
    - app_sync_rates 1
    - app_fps_max 240

filesystem:
    assets:
        - bspviewer
        - base
        - E:\\Steam\\steamapps\\common\\Half-Life\\valve
        - E:\\Steam\\steamapps\\common\\Half-Life\\valve_downloads
    config:
        - bspviewer/cfg
